my_ads:
    pattern:  /app/my-ads
    defaults: { _controller: AdsmanagerBundle:Ads:myAds }
new_ads:
    pattern:  /app/new-ads
    defaults: { _controller: AdsmanagerBundle:Ads:newAds }
edit_ads:
    pattern:  /app/edit-ads/{id}/
    defaults: { _controller: AdsmanagerBundle:Ads:editAds }
delete_ads:
    pattern:  /app/delete-ads/{id}/
    defaults: { _controller: AdsmanagerBundle:Ads:deleteAds }
renew_ads:
    pattern:  /app/renew-ads/{id}/
    defaults: { _controller: AdsmanagerBundle:Ads:renewAds }
new_ads_product:
    pattern:  /app/new-ads-product/{id}/
    defaults: { _controller: AdsmanagerBundle:Product:newAdsProduct }
edit_product_ads:
    pattern:  /app/edit-product-ads/{id}/
    defaults: { _controller: AdsmanagerBundle:Product:editAdsProduct }
delete_product_ads:
    pattern:  /app/delete-product-ads/{id}/
    defaults: { _controller: AdsmanagerBundle:Product:deleteProductAds }
ads_city:
    pattern:  /app/city/{city}/
    defaults: { _controller: PagesBundle:Default:appCity }
show_category:
    pattern:  /app/category/{idCategory}/{idCity}/{range}
    defaults: { _controller: AdsmanagerBundle:AdsCategories:show }
show_category_geolocation:
    pattern:  /app/category/{idCategory}/{idCity}/{latitude}/{longitude}/{range}
    defaults: { _controller: AdsmanagerBundle:AdsCategories:showGeolocation }
show_category_rated:
    pattern:  /app/categoryRated/{idCategory}/{idCity}/{range}
    defaults: { _controller: AdsmanagerBundle:AdsCategories:showRated }
show_category_map:
    pattern:  /app/category/{idCategory}/{idCity}/
    defaults: { _controller: AdsmanagerBundle:AdsCategories:showMap }
show_ad:
    pattern:  /app/ad/{idAd}/{idCity}
    defaults: { _controller: AdsmanagerBundle:Ads:show }
show_ad_map:
    pattern:  /app/ad/{idAd}/{idCity}/
    defaults: { _controller: AdsmanagerBundle:Ads:showMap }
adRate:
  pattern:    /app/ad-rate/
  defaults:   { _controller: AdsmanagerBundle:Ads:Rate }

search_ads:
    pattern:  /app/search/
    defaults: { _controller: AdsmanagerBundle:AdsSearch:search }
search_ads_category:
    pattern:  /app/search/category/{idCategory}/{idCity}/{range}/
    defaults: { _controller: AdsmanagerBundle:AdsSearch:searchCategory }
search_save:
    pattern:  /app/search/save/
    defaults: { _controller: AdsmanagerBundle:AdsSearch:searchSave }

ad_comment:
    pattern:  /app/ad/ad_comment/
    defaults: { _controller: AdsmanagerBundle:Ads:adComment }

edit_comment:
    pattern:  /app/ad/edit_comment/
    defaults: { _controller: AdsmanagerBundle:Ads:editComment }

delete_comment:
    pattern:  /app/delete_comment/
    defaults: { _controller: AdsmanagerBundle:Ads:deleteComment }

date_comment:
    pattern:  /app/add/comment_date/
    defaults: { _controller: AdsmanagerBundle:Ads:dateComment }

paginationAd:
    pattern:  /app/ad/paginationAd/
    defaults: { _controller: AdsmanagerBundle:Ads:paginationAd }

message_emailAds:
    pattern:  /app/ad/messagemailAds/
    defaults: { _controller: AdsmanagerBundle:AdsInbox:emailAds }

inboxemailAds:
    pattern:  /app/ad/inboxEmailAds/
    defaults: { _controller: AdsmanagerBundle:AdsInbox:inboxEmailAds }

inboxList:
    pattern:  /app/ad/inboxList/
    defaults: { _controller: AdsmanagerBundle:AdsInbox:inboxList } 


inboxOpenInboxMessage:
    pattern:  /app/ad/inboxOpenInboxMessage/
    defaults: { _controller: AdsmanagerBundle:AdsInbox:inboxOpenInboxMessage }

inboxSent:
    pattern:  /app/ad/inboxSent/
    defaults: { _controller: AdsmanagerBundle:AdsInbox:inboxSent }

responseMessage:
    pattern:  /app/ad/responseMessage/
    defaults: { _controller: AdsmanagerBundle:AdsInbox:responseMessage }    

saveMessage:
    pattern:  /app/ad/saveMessage/
    defaults: { _controller: AdsmanagerBundle:AdsInbox:saveMessage }     


inboxemailAdsR:
    pattern:  /app/inbox/inboxemailAdsR/{idA}
    defaults: { _controller: AdsmanagerBundle:AdsInbox:inboxemailAdsR }

Message_ListInbox:
     pattern:  /app/inbox/Message_ListInbox/
     defaults: { _controller: AdsmanagerBundle:AdsInbox:message_ListInbox }

Message_SentInbox:
     pattern:  /app/inbox/Message_SentInbox/
     defaults: { _controller: AdsmanagerBundle:AdsInbox:message_SentInbox }

messageOpenInboxAds:
 pattern:  /app/inbox/messageOpenInboxAds/
 defaults: { _controller: AdsmanagerBundle:AdsInbox:messageOpenInboxAds }

Message_ResponseInbox:
     pattern:  /app/inbox/Message_ResponseInbox/
     defaults: { _controller: AdsmanagerBundle:AdsInbox:message_ResponseInbox } 

