SeekerPlus\AdsmanagerBundle\Entity\AdsComments:
    type: entity
    table: ad_comments
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idUser:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: id_user
        idAds:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: id_ads
        dateCreated:
            type: date
            nullable: true
            comment: ''
            column: date_created
        commentAd:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: comment_ad
    lifecycleCallbacks: {  }
